### ISSUE TITLE
Pressing the Link Media button throws: NameError: 'removeDokumentLink' is not defined

### ISSUE THREAD

**Issue by polirritmico** [gkarsay/parlatype-libreoffice-extension#9]
## Summary:
Pressing the `Link Media` button to remove document link throw an is not defined error: 

![screenshot](https://user-images.githubusercontent.com/24460484/172731009-1f7b8e83-5046-43e4-9353-f5dc697b87e6.png)

Just need to fix the typo: https://gist.github.com/polirritmico/4bc51c4dd49c0951c6412c16078a6313

## Steps to reproduce:
Open Parlatype from Writer, Open an audio file, press `Link Media`, then press `Link Media` again.

## System info: 
Parlatype LibreOffice Extension 3.1.1 (oxt)
Version: 7.2.6.2 / LibreOffice Community
Build ID: 20(Build:2)
CPU threads: 8; OS: Linux 5.15; UI render: default; VCL: kf5 (cairo+xcb)
Locale: es-CL (es_CL.UTF-8); UI: es-ES
Gentoo official package
Calc: threaded

**Comment by gkarsay** [comment]
Thank you very much! This bug was introduced right before v3.1 with commit 9610de0def9ecb133c62c549ea20bf2ace066c4c. I will have a serious talk with my Quality Assurance Department, that's quite an embarrassing situation for them. I will also talk to my Release Manager, I will try to convince him to make a bug release.
